# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2013-01-01 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cedula_alumno', models.CharField(blank=True, max_length=8)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=70)),
                ('Fecha_nacimiento', models.DateField(verbose_name='Fecha De Nacimiento')),
                ('Sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default=0, max_length=30)),
                ('Direccion_habitacion', models.CharField(max_length=70)),
                ('Telefono', models.CharField(blank=True, max_length=11)),
                ('Celular', models.CharField(blank=True, max_length=11)),
                ('Nivel_instruccion', models.CharField(max_length=70)),
                ('Email', models.EmailField(max_length=254)),
                ('Institucion_cursante', models.CharField(max_length=70)),
                ('Curso_realizar', models.CharField(max_length=50)),
                ('Cursa_otra_actividad', models.CharField(blank=True, max_length=50)),
                ('Musica', models.BooleanField(default=False)),
                ('Danza', models.BooleanField(default=False)),
                ('Teatro', models.BooleanField(default=False)),
                ('Artes_Plasticas', models.BooleanField(default=False)),
                ('cedula_representante', models.CharField(blank=True, max_length=8, null=True, verbose_name='Cedula Del Representante')),
                ('Nombre_Repre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre')),
                ('Apellid_Repre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido')),
                ('Telefono_repre', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_hijo', models.ManyToManyField(to='registro.Registro')),
            ],
        ),
    ]
