# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-07 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('ci', models.CharField(max_length=8, unique=True, verbose_name='Cédula')),
                ('username', models.CharField(blank=True, default='Cédula', max_length=40, verbose_name='username')),
                ('first_name', models.CharField(max_length=40, verbose_name='first name')),
                ('last_name', models.CharField(max_length=40, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('is_director', models.BooleanField(default=False, verbose_name='Director')),
                ('is_secretaria_danza', models.BooleanField(default=False, verbose_name='Secretaria De Danza')),
                ('is_secretaria_teatro', models.BooleanField(default=False, verbose_name='Secretaria De Teatro')),
                ('is_secretaria_musica', models.BooleanField(default=False, verbose_name='Secretaria De Musica')),
                ('is_secretaria_artes', models.BooleanField(default=False, verbose_name='Secretaria De Artes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff Status')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superuser Status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sate Joined')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
