# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2013-01-01 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(blank=True, max_length=8, verbose_name='username'),
        ),
    ]
