# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2013-03-01 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0003_auto_20180226_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='url',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
