# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2013-03-01 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0004_actividad_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='url',
        ),
    ]
