# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2013-01-01 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('Numero', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Actividad', models.CharField(max_length=50)),
                ('catedra', models.CharField(choices=[('Danza', 'Danza'), ('Musica', 'Musica'), ('Teatro', 'Teatro'), ('Artes Plasticas', 'Artes Plasticas')], max_length=30)),
                ('descripcion', models.CharField(max_length=250)),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
