# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2013-01-01 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actividad',
        ),
    ]
